FwwUCenter/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FwwUCenter.Controllers
{
    [Authorize]
    public class AccountController : BaseController
    {
        public ActionResult Account()
        {
            return View();
        }

        public ActionResult UserInfo()
        {
            ViewBag.Message = "";

            return View();
        }
        public ActionResult UserFinInfo()
        {
            ViewBag.Message = "";

            return View();
        }
        public ActionResult UserCard()
        {
            ViewBag.Message = "";

            return View();
        }
        public ActionResult MyCompany()
        {
            ViewBag.Message = "";

            return View();
        }
        public ActionResult MyQualification()
        {
            ViewBag.Message = "";

            return View();
        }
        public ActionResult MyPwd()
        {
            ViewBag.Message = "";

            return View();


        }
        public ActionResult MyPayPwd()
        {
            ViewBag.Message = "";

            return View();
        }
        public ActionResult MyAppealPayPwd()
        {
            ViewBag.Message = "";

            return View();
        }
        public ActionResult MyMembers()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

FwwUCenter/Controllers/BaseController.cs
using System;
using System.Web.Mvc;

namespace FwwUCenter.Controllers
{
    public class BaseController : Controller
    {
  
    }
    //public class MemberAuthorizeAttribute : ActionFilterAttribute
    //{
    //    /// <summary>
    //    /// 拦截会员是否登录验证
    //    /// </summary>
    //    /// <param name="filterContext"></param>
    //    public override void OnActionExecuting(ActionExecutingContext filterContext)
    //    {
    //        var session = filterContext.RequestContext.HttpContext.Session;
    //        var response = filterContext.RequestContext.HttpContext.Response;
    //        var request = filterContext.RequestContext.HttpContext.Request;
    //        // 验证微是否已经登录
    //        if (session["loginuserid"] == null)
    //        {
    //            // 跳转到登陆页
    //            response.Redirect("/Login/Login?RedUrl=" + request.Url.AbsoluteUri + "&t=" + DateTime.Now.ToString("yyyyMMddHHmmss"));
    //        }
    //        else
    //        {

    //            // 当前用户已登录，继续访问页面
    //            base.OnActionExecuting(filterContext);
    //        }
           
    //    }
          
    //}
}

FwwUCenter/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FwwUCenter.Controllers
{
    [Authorize]
    public class CouponController : BaseController
    {
        public ActionResult MyCoupon()
        {
            //我的券包含 多少张 已经排队  未排队
            //券获取时间 排队时间等
            //队列查看明细
            return View();
        }

        public ActionResult AllCoupon()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

        public ActionResult LineupCoupon()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

        public ActionResult TransferCoupon()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

        public ActionResult BuyCoupon()
        {
            ViewBag.Message = "Your page.";

            return View();
        }
    }
}

FwwUCenter/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FwwUCenter.Controllers
{
    [Authorize]
    public class DashboardController : BaseController
    {

        public ActionResult Dashboard()
        {
            return View();
        }

        
        public ActionResult Noti()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        
        public ActionResult Resourcecenter()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FwwUCenter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FwwUCenter.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(string UserName, string Password)
        {
            //UserName.ToUpper() == "ZCZCZY" && Password.ToUpper() == "ZCZCZY2015"
            if (!String.IsNullOrEmpty(UserName))
            {
                FormsAuthentication.SetAuthCookie(UserName, false);
                return Redirect("/Dashboard/Dashboard");
            }
            return Redirect("/");
        }

         
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }

        public ActionResult ForgetPWD()
        {
            return View();
        }

        public ActionResult NewUser()
        {
            return View();
        }
        

    }
}

FwwUCenter/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FwwUCenter.Controllers
{
    [Authorize]
    public class OrdersController : BaseController
    {
        public ActionResult MyOrders()
        {
            //我的钱包 包含 电子钱包余额\车票等等信息
            return View();
        }

        public ActionResult NewOrder()
        {
            //我的钱包 包含 电子钱包余额\车票等等信息
            return View();
        }
    }
}

FwwUCenter/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WorkflowEngine;

namespace FwwUCenter.Controllers
{
    [Authorize]
    public class TicketController : BaseController
    {
        public ActionResult NewCompany()
        {
            //我的钱包 包含 电子钱包余额\车票等等信息
            return View();
        }

        public ActionResult NewAgent()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

        public ActionResult NewOperationCenter()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

        public ActionResult MyTicket()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

        [HttpPost]
        public ActionResult NewCompanyTicket(string wfCode)
        {
            //UserName.ToUpper() == "ZCZCZY" && Password.ToUpper() == "ZCZCZY2015"
            if (!String.IsNullOrEmpty(User.Identity.Name))
            {
                WFService wfService = new WFService();
                int temp = wfService.NewTicket(User.Identity.Name,"A");
                if (temp == 0)
                {
                    ViewBag.Message = "提交成功";
                }
                else
                {
                    ViewBag.Message = "提交失败";
                }
            }
            return Redirect("/Ticket/NewCompany");
        }



    }
}

FwwUCenter/Controllers/WalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FwwUCenter.Controllers
{
    public class WalletController : BaseController
    {
      [Authorize]
        public ActionResult MyWallet()
        {
            //我的钱包 包含 电子钱包余额\车票等等信息
            return View();
        }

        
        public ActionResult MyBill()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

        
        public ActionResult TransferAcount()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

         
        public ActionResult WithdrawCash()
        {
            ViewBag.Message = "Your page.";

            return View();
        }

         
        public ActionResult WalletPurchase()
        {
            ViewBag.Message = "Your page.";

            return View();
        }
    }
}

FwwUCenter/Views/Home/ForgetPWD.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>


@{
    ViewBag.Title = "忘记密码";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>@Html.ActionLink("登录", "Login", "Account")</p>

FwwUCenter/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title 中国消费服务网会员中心</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <div class="text-center">
            <h1></h1>
            <div class="row">
                <div class="col-md-5 col-md-offset-3 ">
                    <div class="panel panel-default">
                        <div class="panel-heading"><p class="help-block-left">会员中心登录</p></div>
                        <div class="panel-body">
                            <form role="form" class="form-vertical" method="post" action="/Home/SignIn">
                                <br />
                                <p class="help-block-right">

                                    <label class="radio-inline">
                                        <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1" checked>用户名登录
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> 会员卡登录
                                    </label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="/Home/NewUser">快速注册</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/Home/ForgetPWD">忘记密码</a>
                                </p>
                                <br />
                                <div class="form-group">
                                    <label class="sr-only" for="Username">Username</label>
                                    <input type="text" class="form-control input-lg" name="UserName" placeholder="用户名 或 会员卡号" autofocus>
                                </div>

                                <div class="form-group">
                                    <label class="sr-only" for="Password">Password</label>
                                    <input type="password" class="form-control input-lg" name="Password" placeholder="密码">
                                </div>

                                <button type="submit" class="btn btn-success btn-lg btn-block ">登录</button>
                                <br />

                               

                                <br />
                            </form>
                        </div>
                    </div>
                       
                </div>
                <div class="col-md-5 col-md-offset-3 ">
                    
                </div>
            </div>
        </div>
    </div>
            
</body>
</html>

FwwUCenter/Views/Home/NewUser.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

@{
    ViewBag.Title = "快速注册";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>@Html.ActionLink("登录", "Login", "Account")</p>

FwwUCenter/Views/Ticket/MyTicket.cshtml
@{
    ViewBag.Title = "我的工单";
}
<h2>@ViewBag.Title.</h2>

<div class="thumbnail">
    <img src="~/Content/image/Icon/ywbl.jpg" />

    <div class="caption">
        <ul class="list-group">
            <li class="list-group-item">@Html.ActionLink("商家申请", "NewCompany", "Ticket")</li>
            <li class="list-group-item">@Html.ActionLink("代理商申请", "NewAgent", "Ticket")</li>
            <li class="list-group-item">@Html.ActionLink("运营中心申请", "NewOperationCenter", "Ticket")</li>
        </ul>

    </div>
</div>

FwwUCenter/Views/Ticket/NewAgent.cshtml
@{
    ViewBag.Title = "代理商申请";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>公告</p>

FwwUCenter/Views/Ticket/NewOperationCenter.cshtml
@{
    ViewBag.Title = "运营中心申请";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>